# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-08-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=300)),
                ('content', models.CharField(blank=True, max_length=300)),
                ('scanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scandetails', to='scan.Scan')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
