# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-08-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(blank=True, max_length=300)),
                ('cardNumber', models.IntegerField(blank=True)),
                ('cvv', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('transactionCode', models.CharField(blank=True, max_length=300)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.Order')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
